## Persiapan Data
Pada tahap ini dilakukan proses pengambilan dataset dari Google Drive. Dataset yang digunakan terdiri dari data training dan data testing.

Data training digunakan untuk membangun model, sedangkan data testing digunakan untuk melakukan prediksi kualitas anggur.

In [59]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [60]:
import pandas as pd

train = pd.read_csv('/content/drive/MyDrive/UTS DATMIN/data_training.csv')
test = pd.read_csv('/content/drive/MyDrive/UTS DATMIN/data_testing.csv')

## Eksplorasi Data
Dilakukan peninjauan awal terhadap dataset untuk melihat struktur data dan memastikan data telah terbaca dengan baik.

In [61]:
train.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.3,0.740,0.08,1.7,0.094,10.0,45.0,0.99576,3.24,0.50,9.8,5,1366
1,8.1,0.575,0.22,2.1,0.077,12.0,65.0,0.99670,3.29,0.51,9.2,5,103
2,10.1,0.430,0.40,2.6,0.092,13.0,52.0,0.99834,3.22,0.64,10.0,7,942
3,12.9,0.500,0.55,2.8,0.072,7.0,24.0,1.00012,3.09,0.68,10.9,6,811
4,8.4,0.360,0.32,2.2,0.081,32.0,79.0,0.99640,3.30,0.72,11.0,6,918

## Pembersihan Data
Dilakukan pengecekan terhadap missing value untuk memastikan tidak ada data kosong pada dataset yang dapat mempengaruhi hasil model.

Berdasarkan hasil pengecekan, tidak ditemukan missing value pada setiap kolom, sehingga data dapat langsung digunakan tanpa proses penanganan data kosong.

In [62]:
train.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

## Pemisahan Fitur dan Target
Pada tahap ini dilakukan pemisahan antara fitur (X) dan target (y). Fitur berisi variabel independen yang digunakan untuk prediksi, sedangkan target adalah nilai kualitas anggur yang akan diprediksi.

In [63]:
X = train.drop(["quality", "Id"], axis=1)
y = train["quality"]

## Pembagian Data
Data dibagi menjadi data training dan data validation dengan perbandingan 80% untuk training dan 20% untuk validation. Hal ini dilakukan untuk menguji performa model.

In [64]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

## Pemodelan
Model yang digunakan adalah Random Forest Classifier. Model ini dipilih karena mampu menangani data dengan baik dan memiliki performa yang cukup stabil dalam klasifikasi.

In [65]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

## Evaluasi Model
Model dievaluasi menggunakan metrik akurasi untuk mengetahui seberapa baik model dalam memprediksi data validation.

In [66]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_val)
print("Akurasi:", accuracy_score(y_val, y_pred))

Akurasi: 0.6162790697674418

## Prediksi Data Testing
Model digunakan untuk memprediksi kualitas anggur pada data testing yang tidak memiliki label.

In [67]:
test_X = test.drop("Id", axis=1)
pred_test = model.predict(test_X)

## Penyimpanan Hasil
Hasil prediksi disimpan dalam file CSV yang berisi kolom Id dan quality sesuai dengan ketentuan tugas.

Berdasarkan hasil prediksi, model mampu menghasilkan nilai kualitas anggur yang kemudian disimpan dalam file CSV untuk keperluan pengumpulan tugas.

In [69]:
hasil.to_csv("hasilprediksi_151.csv", index=False)

In [70]:
files.download("hasilprediksi_151.csv")

In [71]:
hasil.head()

     Id  quality
0   222        5
1  1514        5
2   417        5
3   754        5
4   516        5

In [72]:
pd.read_csv("hasilprediksi_151.csv").head()

     Id  quality
0   222        5
1  1514        5
2   417        5
3   754        5
4   516        5

In [73]:
hasil["quality"].value_counts()

quality
5    136
6    119
7     31
Name: count, dtype: int64

In [74]:
hasil.columns

Index(['Id', 'quality'], dtype='object')

In [75]:
hasil.head()
hasil["quality"].value_counts()

quality
5    136
6    119
7     31
Name: count, dtype: int64